############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Documentation"
url = "https://docs.plant-it.org"
weight = 2


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Documentation"
url = "https://docs.plant-it.org"
weight = 2
