arb-dir: lib/l10n
output-dir: lib/l10n/generated
output-localization-file: app_localizations.dart
template-arb-file: app_en.arb
nullable-getter: false
output-class: L
untranslated-messages-file: l10n_missing.txt