body:
  - type: textarea
    attributes:
      label: Question
      description: Please provide the question here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Local environment
      description: If applicable, please provide additional information related to the environment you are using.
      placeholder: |
        1. app version
        2. phone model
        3. phone OS version
