name: 🐛 Bug Report
description: Report a bug in Plant-it.
labels:
  - "Type: Bug"
  - "Status: Created"
body:
  - type: markdown
    attributes:
      value: |
        Please use this only if you identified a real error in the application. If you need help, please use the [discussion forum](https://github.com/MDeLuise/plant-it/discussions).
        Thanks for taking the time to fill out this bug report!
  
  # General description
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the application error is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce
      description: How can the error be reproduced?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  # App details
  - type: input
    id: plant-it-version
    attributes:
      label: Plant-it version
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: plant-it-setup-os
    attributes:
      label: Phone Model and Operating System version
      description: In which operating system does the app run?
    validations:
      required: true
