name: Feature Request
description: Request a feature or enhancement in Plant-it
body:
  - type: checkboxes
    attributes:
      label: Avoid duplicated feature requests
      description: Please check if someone already required this
      options:
        - label: There are no open or closed feature requests that are related to this request
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please describe your feature request
      placeholder: |
        - I would like Plant-it to do (thing).
        - What if you would add feature (feature here)?
        - Plant-it doesn't do (thing).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution
      description: Describe what your feature would add to Plant-it.

  - type: textarea
    attributes:
      label: What are alternatives?
      description: Please describe what alternatives currently exist.

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.


