name: Ask a question
description: Ask and answer questions here.
body:
  - type: textarea
    attributes:
      label: Question
      description: Please provide the question here.
    validations:
      required: true
