// Mocks generated by Mockito 5.4.6 from annotations
// in plant_it/test/data/plant_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i7;

import 'package:drift/drift.dart' as _i2;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:drift/src/runtime/types/mapping.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:plant_it/database/database.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMigrationStrategy_0 extends _i1.SmartFake
    implements _i2.MigrationStrategy {
  _FakeMigrationStrategy_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EventTypesTable_1 extends _i1.SmartFake
    implements _i3.$EventTypesTable {
  _Fake$EventTypesTable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SpeciesTable_2 extends _i1.SmartFake implements _i3.$SpeciesTable {
  _Fake$SpeciesTable_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$PlantsTable_3 extends _i1.SmartFake implements _i3.$PlantsTable {
  _Fake$PlantsTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SpeciesSynonymsTable_4 extends _i1.SmartFake
    implements _i3.$SpeciesSynonymsTable {
  _Fake$SpeciesSynonymsTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SpeciesCareTable_5 extends _i1.SmartFake
    implements _i3.$SpeciesCareTable {
  _Fake$SpeciesCareTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EventsTable_6 extends _i1.SmartFake implements _i3.$EventsTable {
  _Fake$EventsTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$RemindersTable_7 extends _i1.SmartFake
    implements _i3.$RemindersTable {
  _Fake$RemindersTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ImagesTable_8 extends _i1.SmartFake implements _i3.$ImagesTable {
  _Fake$ImagesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$UserSettingsTable_9 extends _i1.SmartFake
    implements _i3.$UserSettingsTable {
  _Fake$UserSettingsTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AppDatabaseManager_10 extends _i1.SmartFake
    implements _i3.$AppDatabaseManager {
  _Fake$AppDatabaseManager_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_11 extends _i1.SmartFake
    implements _i2.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_12 extends _i1.SmartFake
    implements _i2.GeneratedDatabase {
  _FakeGeneratedDatabase_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_13 extends _i1.SmartFake
    implements _i2.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_14 extends _i1.SmartFake
    implements _i2.DatabaseConnection {
  _FakeDatabaseConnection_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_15 extends _i1.SmartFake implements _i2.QueryExecutor {
  _FakeQueryExecutor_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_16 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_17 extends _i1.SmartFake
    implements _i2.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_18 extends _i1.SmartFake implements _i2.Migrator {
  _FakeMigrator_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_19<T1> extends _i1.SmartFake implements _i5.Future<T1> {
  _FakeFuture_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_20<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.InsertStatement<T1, D1> {
  _FakeInsertStatement_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_21<T extends _i2.Table, D> extends _i1.SmartFake
    implements _i2.UpdateStatement<T, D> {
  _FakeUpdateStatement_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_22<T1 extends _i2.HasResultSet, D>
    extends _i1.SmartFake implements _i2.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_23<FirstT extends _i2.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i2.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_24<Row> extends _i1.SmartFake
    implements _i2.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_25<T1 extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_26<T> extends _i1.SmartFake implements _i2.Selectable<T> {
  _FakeSelectable_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_27 extends _i1.SmartFake
    implements _i2.GenerationContext {
  _FakeGenerationContext_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedColumn_28<T extends Object> extends _i1.SmartFake
    implements _i2.GeneratedColumn<T> {
  _FakeGeneratedColumn_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedColumnWithTypeConverter_29<D, S extends Object> extends _i1
    .SmartFake implements _i2.GeneratedColumnWithTypeConverter<D, S> {
  _FakeGeneratedColumnWithTypeConverter_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerificationContext_30 extends _i1.SmartFake
    implements _i2.VerificationContext {
  _FakeVerificationContext_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlant_31 extends _i1.SmartFake implements _i3.Plant {
  _FakePlant_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColumnBuilder_32<T extends Object> extends _i1.SmartFake
    implements _i2.ColumnBuilder<T> {
  _FakeColumnBuilder_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResultSetImplementation_33<Tbl, Row> extends _i1.SmartFake
    implements _i2.ResultSetImplementation<Tbl, Row> {
  _FakeResultSetImplementation_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTableInfo_34<TableDsl extends _i2.Table, D1> extends _i1.SmartFake
    implements _i2.TableInfo<TableDsl, D1> {
  _FakeTableInfo_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$EventTypesTableTableManager_35 extends _i1.SmartFake
    implements _i3.$$EventTypesTableTableManager {
  _Fake$$EventTypesTableTableManager_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$SpeciesTableTableManager_36 extends _i1.SmartFake
    implements _i3.$$SpeciesTableTableManager {
  _Fake$$SpeciesTableTableManager_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$PlantsTableTableManager_37 extends _i1.SmartFake
    implements _i3.$$PlantsTableTableManager {
  _Fake$$PlantsTableTableManager_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$SpeciesSynonymsTableTableManager_38 extends _i1.SmartFake
    implements _i3.$$SpeciesSynonymsTableTableManager {
  _Fake$$SpeciesSynonymsTableTableManager_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$SpeciesCareTableTableManager_39 extends _i1.SmartFake
    implements _i3.$$SpeciesCareTableTableManager {
  _Fake$$SpeciesCareTableTableManager_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$EventsTableTableManager_40 extends _i1.SmartFake
    implements _i3.$$EventsTableTableManager {
  _Fake$$EventsTableTableManager_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$RemindersTableTableManager_41 extends _i1.SmartFake
    implements _i3.$$RemindersTableTableManager {
  _Fake$$RemindersTableTableManager_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$ImagesTableTableManager_42 extends _i1.SmartFake
    implements _i3.$$ImagesTableTableManager {
  _Fake$$ImagesTableTableManager_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$$UserSettingsTableTableManager_43 extends _i1.SmartFake
    implements _i3.$$UserSettingsTableTableManager {
  _Fake$$UserSettingsTableTableManager_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i3.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);

  @override
  _i2.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_0(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i2.MigrationStrategy);

  @override
  _i3.$EventTypesTable get eventTypes => (super.noSuchMethod(
        Invocation.getter(#eventTypes),
        returnValue: _Fake$EventTypesTable_1(
          this,
          Invocation.getter(#eventTypes),
        ),
      ) as _i3.$EventTypesTable);

  @override
  _i3.$SpeciesTable get species => (super.noSuchMethod(
        Invocation.getter(#species),
        returnValue: _Fake$SpeciesTable_2(
          this,
          Invocation.getter(#species),
        ),
      ) as _i3.$SpeciesTable);

  @override
  _i3.$PlantsTable get plants => (super.noSuchMethod(
        Invocation.getter(#plants),
        returnValue: _Fake$PlantsTable_3(
          this,
          Invocation.getter(#plants),
        ),
      ) as _i3.$PlantsTable);

  @override
  _i3.$SpeciesSynonymsTable get speciesSynonyms => (super.noSuchMethod(
        Invocation.getter(#speciesSynonyms),
        returnValue: _Fake$SpeciesSynonymsTable_4(
          this,
          Invocation.getter(#speciesSynonyms),
        ),
      ) as _i3.$SpeciesSynonymsTable);

  @override
  _i3.$SpeciesCareTable get speciesCare => (super.noSuchMethod(
        Invocation.getter(#speciesCare),
        returnValue: _Fake$SpeciesCareTable_5(
          this,
          Invocation.getter(#speciesCare),
        ),
      ) as _i3.$SpeciesCareTable);

  @override
  _i3.$EventsTable get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _Fake$EventsTable_6(
          this,
          Invocation.getter(#events),
        ),
      ) as _i3.$EventsTable);

  @override
  _i3.$RemindersTable get reminders => (super.noSuchMethod(
        Invocation.getter(#reminders),
        returnValue: _Fake$RemindersTable_7(
          this,
          Invocation.getter(#reminders),
        ),
      ) as _i3.$RemindersTable);

  @override
  _i3.$ImagesTable get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: _Fake$ImagesTable_8(
          this,
          Invocation.getter(#images),
        ),
      ) as _i3.$ImagesTable);

  @override
  _i3.$UserSettingsTable get userSettings => (super.noSuchMethod(
        Invocation.getter(#userSettings),
        returnValue: _Fake$UserSettingsTable_9(
          this,
          Invocation.getter(#userSettings),
        ),
      ) as _i3.$UserSettingsTable);

  @override
  _i3.$AppDatabaseManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _Fake$AppDatabaseManager_10(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i3.$AppDatabaseManager);

  @override
  Iterable<_i2.TableInfo<_i2.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i2.TableInfo<_i2.Table, Object?>>[],
      ) as Iterable<_i2.TableInfo<_i2.Table, Object?>>);

  @override
  List<_i2.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i2.DatabaseSchemaEntity>[],
      ) as List<_i2.DatabaseSchemaEntity>);

  @override
  _i2.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_11(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i2.StreamQueryUpdateRules);

  @override
  _i2.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_12(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.GeneratedDatabase);

  @override
  _i2.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_13(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.DriftDatabaseOptions);

  @override
  _i2.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_14(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i2.DatabaseConnection);

  @override
  _i2.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i6.dummyValue<_i2.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i2.SqlTypes);

  @override
  _i2.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_15(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i2.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_16(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i2.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i5.Future<void> initEventTypes() => (super.noSuchMethod(
        Invocation.method(
          #initEventTypes,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> initDummyData() => (super.noSuchMethod(
        Invocation.method(
          #initDummyData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> createAndSaveImages() => (super.noSuchMethod(
        Invocation.method(
          #createAndSaveImages,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i2.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_18(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i2.Migrator);

  @override
  _i5.Future<void> beforeOpen(
    _i2.QueryExecutor? executor,
    _i2.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i5.Stream<T>.empty(),
      ) as _i5.Stream<T>);

  @override
  T alias<T, D>(
    _i2.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i6.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i2.TableInfo<_i2.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i2.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Stream<Set<_i2.TableUpdate>> tableUpdates(
          [_i2.TableUpdateQuery? query = const _i2.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i5.Stream<Set<_i2.TableUpdate>>.empty(),
      ) as _i5.Stream<Set<_i2.TableUpdate>>);

  @override
  _i5.Future<T> doWhenOpened<T>(
          _i5.FutureOr<T> Function(_i2.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.InsertStatement<T, D> into<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_20<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i2.InsertStatement<T, D>);

  @override
  _i2.UpdateStatement<Tbl, R> update<Tbl extends _i2.Table, R>(
          _i2.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_21<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i2.UpdateStatement<Tbl, R>);

  @override
  _i2.SimpleSelectStatement<T, R> select<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_22<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.SimpleSelectStatement<T, R>);

  @override
  _i2.JoinedSelectStatement<T, R> selectOnly<T extends _i2.HasResultSet, R>(
    _i2.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_23<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i2.JoinedSelectStatement<T, R>);

  @override
  _i2.BaseSelectStatement<_i2.TypedResult> selectExpressions(
          Iterable<_i2.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_24<_i2.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i2.BaseSelectStatement<_i2.TypedResult>);

  @override
  _i2.DeleteStatement<T, D> delete<T extends _i2.Table, D>(
          _i2.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_25<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i2.DeleteStatement<T, D>);

  @override
  _i5.Future<int> customUpdate(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> customInsert(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i2.QueryRow>> customWriteReturning(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i2.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i5.Future<List<_i2.QueryRow>>.value(<_i2.QueryRow>[]),
      ) as _i5.Future<List<_i2.QueryRow>>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelect(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_26<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i2.Selectable<_i2.QueryRow> customSelectQuery(
    String? query, {
    List<_i2.Variable<Object>>? variables = const [],
    Set<_i2.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_26<_i2.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i2.Selectable<_i2.QueryRow>);

  @override
  _i5.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> transaction<T>(
    _i5.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<T> exclusively<T>(_i5.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i5.Future<void> batch(_i5.FutureOr<void> Function(_i2.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T> runWithInterceptor<T>(
    _i5.Future<T> Function()? action, {
    required _i2.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i5.Future<T>.value(v),
            ) ??
            _FakeFuture_19<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i5.Future<T>);

  @override
  _i2.GenerationContext $write(
    _i2.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  _i2.GenerationContext $writeInsertable(
    _i2.TableInfo<_i2.Table, dynamic>? table,
    _i2.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);
}

/// A class which mocks [$PlantsTable].
///
/// See the documentation for Mockito's code generation for more information.
class Mock$PlantsTable extends _i1.Mock implements _i3.$PlantsTable {
  Mock$PlantsTable() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_12(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.GeneratedDatabase);

  @override
  _i2.GeneratedColumn<int> get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _FakeGeneratedColumn_28<int>(
          this,
          Invocation.getter(#id),
        ),
      ) as _i2.GeneratedColumn<int>);

  @override
  _i2.GeneratedColumn<String> get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _FakeGeneratedColumn_28<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as _i2.GeneratedColumn<String>);

  @override
  _i2.GeneratedColumn<DateTime> get startDate => (super.noSuchMethod(
        Invocation.getter(#startDate),
        returnValue: _FakeGeneratedColumn_28<DateTime>(
          this,
          Invocation.getter(#startDate),
        ),
      ) as _i2.GeneratedColumn<DateTime>);

  @override
  _i2.GeneratedColumn<String> get note => (super.noSuchMethod(
        Invocation.getter(#note),
        returnValue: _FakeGeneratedColumn_28<String>(
          this,
          Invocation.getter(#note),
        ),
      ) as _i2.GeneratedColumn<String>);

  @override
  _i2.GeneratedColumn<String> get location => (super.noSuchMethod(
        Invocation.getter(#location),
        returnValue: _FakeGeneratedColumn_28<String>(
          this,
          Invocation.getter(#location),
        ),
      ) as _i2.GeneratedColumn<String>);

  @override
  _i2.GeneratedColumn<double> get price => (super.noSuchMethod(
        Invocation.getter(#price),
        returnValue: _FakeGeneratedColumn_28<double>(
          this,
          Invocation.getter(#price),
        ),
      ) as _i2.GeneratedColumn<double>);

  @override
  _i2.GeneratedColumn<String> get seller => (super.noSuchMethod(
        Invocation.getter(#seller),
        returnValue: _FakeGeneratedColumn_28<String>(
          this,
          Invocation.getter(#seller),
        ),
      ) as _i2.GeneratedColumn<String>);

  @override
  _i2.GeneratedColumn<DateTime> get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _FakeGeneratedColumn_28<DateTime>(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as _i2.GeneratedColumn<DateTime>);

  @override
  _i2.GeneratedColumn<int> get species => (super.noSuchMethod(
        Invocation.getter(#species),
        returnValue: _FakeGeneratedColumn_28<int>(
          this,
          Invocation.getter(#species),
        ),
      ) as _i2.GeneratedColumn<int>);

  @override
  _i2.GeneratedColumnWithTypeConverter<_i3.AvatarMode, String> get avatarMode =>
      (super.noSuchMethod(
        Invocation.getter(#avatarMode),
        returnValue:
            _FakeGeneratedColumnWithTypeConverter_29<_i3.AvatarMode, String>(
          this,
          Invocation.getter(#avatarMode),
        ),
      ) as _i2.GeneratedColumnWithTypeConverter<_i3.AvatarMode, String>);

  @override
  List<_i2.GeneratedColumn<Object>> get $columns => (super.noSuchMethod(
        Invocation.getter(#$columns),
        returnValue: <_i2.GeneratedColumn<Object>>[],
      ) as List<_i2.GeneratedColumn<Object>>);

  @override
  String get aliasedName => (super.noSuchMethod(
        Invocation.getter(#aliasedName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#aliasedName),
        ),
      ) as String);

  @override
  String get actualTableName => (super.noSuchMethod(
        Invocation.getter(#actualTableName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#actualTableName),
        ),
      ) as String);

  @override
  Set<_i2.GeneratedColumn<Object>> get $primaryKey => (super.noSuchMethod(
        Invocation.getter(#$primaryKey),
        returnValue: <_i2.GeneratedColumn<Object>>{},
      ) as Set<_i2.GeneratedColumn<Object>>);

  @override
  bool get withoutRowId => (super.noSuchMethod(
        Invocation.getter(#withoutRowId),
        returnValue: false,
      ) as bool);

  @override
  bool get dontWriteConstraints => (super.noSuchMethod(
        Invocation.getter(#dontWriteConstraints),
        returnValue: false,
      ) as bool);

  @override
  bool get isStrict => (super.noSuchMethod(
        Invocation.getter(#isStrict),
        returnValue: false,
      ) as bool);

  @override
  Set<_i2.Column<Object>> get primaryKey => (super.noSuchMethod(
        Invocation.getter(#primaryKey),
        returnValue: <_i2.Column<Object>>{},
      ) as Set<_i2.Column<Object>>);

  @override
  List<Set<_i2.GeneratedColumn<Object>>> get uniqueKeys => (super.noSuchMethod(
        Invocation.getter(#uniqueKeys),
        returnValue: <Set<_i2.GeneratedColumn<Object>>>[],
      ) as List<Set<_i2.GeneratedColumn<Object>>>);

  @override
  List<String> get customConstraints => (super.noSuchMethod(
        Invocation.getter(#customConstraints),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i3.$PlantsTable get asDslTable => (super.noSuchMethod(
        Invocation.getter(#asDslTable),
        returnValue: _Fake$PlantsTable_3(
          this,
          Invocation.getter(#asDslTable),
        ),
      ) as _i3.$PlantsTable);

  @override
  String get entityName => (super.noSuchMethod(
        Invocation.getter(#entityName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#entityName),
        ),
      ) as String);

  @override
  Map<String, _i2.GeneratedColumn<Object>> get columnsByName =>
      (super.noSuchMethod(
        Invocation.getter(#columnsByName),
        returnValue: <String, _i2.GeneratedColumn<Object>>{},
      ) as Map<String, _i2.GeneratedColumn<Object>>);

  @override
  _i2.VerificationContext validateIntegrity(
    _i2.Insertable<_i3.Plant>? instance, {
    bool? isInserting = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateIntegrity,
          [instance],
          {#isInserting: isInserting},
        ),
        returnValue: _FakeVerificationContext_30(
          this,
          Invocation.method(
            #validateIntegrity,
            [instance],
            {#isInserting: isInserting},
          ),
        ),
      ) as _i2.VerificationContext);

  @override
  _i3.Plant map(
    Map<String, dynamic>? data, {
    String? tablePrefix,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #map,
          [data],
          {#tablePrefix: tablePrefix},
        ),
        returnValue: _FakePlant_31(
          this,
          Invocation.method(
            #map,
            [data],
            {#tablePrefix: tablePrefix},
          ),
        ),
      ) as _i3.Plant);

  @override
  _i3.$PlantsTable createAlias(String? alias) => (super.noSuchMethod(
        Invocation.method(
          #createAlias,
          [alias],
        ),
        returnValue: _Fake$PlantsTable_3(
          this,
          Invocation.method(
            #createAlias,
            [alias],
          ),
        ),
      ) as _i3.$PlantsTable);

  @override
  _i2.ColumnBuilder<int> integer() => (super.noSuchMethod(
        Invocation.method(
          #integer,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<int>(
          this,
          Invocation.method(
            #integer,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<int>);

  @override
  _i2.ColumnBuilder<BigInt> int64() => (super.noSuchMethod(
        Invocation.method(
          #int64,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<BigInt>(
          this,
          Invocation.method(
            #int64,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<BigInt>);

  @override
  _i2.ColumnBuilder<int> intEnum<T extends Enum>() => (super.noSuchMethod(
        Invocation.method(
          #intEnum,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<int>(
          this,
          Invocation.method(
            #intEnum,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<int>);

  @override
  _i2.ColumnBuilder<String> text() => (super.noSuchMethod(
        Invocation.method(
          #text,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<String>(
          this,
          Invocation.method(
            #text,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<String>);

  @override
  _i2.ColumnBuilder<String> textEnum<T extends Enum>() => (super.noSuchMethod(
        Invocation.method(
          #textEnum,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<String>(
          this,
          Invocation.method(
            #textEnum,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<String>);

  @override
  _i2.ColumnBuilder<bool> boolean() => (super.noSuchMethod(
        Invocation.method(
          #boolean,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<bool>(
          this,
          Invocation.method(
            #boolean,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<bool>);

  @override
  _i2.ColumnBuilder<DateTime> dateTime() => (super.noSuchMethod(
        Invocation.method(
          #dateTime,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<DateTime>(
          this,
          Invocation.method(
            #dateTime,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<DateTime>);

  @override
  _i2.ColumnBuilder<_i7.Uint8List> blob() => (super.noSuchMethod(
        Invocation.method(
          #blob,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<_i7.Uint8List>(
          this,
          Invocation.method(
            #blob,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<_i7.Uint8List>);

  @override
  _i2.ColumnBuilder<double> real() => (super.noSuchMethod(
        Invocation.method(
          #real,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<double>(
          this,
          Invocation.method(
            #real,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<double>);

  @override
  _i2.ColumnBuilder<_i2.DriftAny> sqliteAny() => (super.noSuchMethod(
        Invocation.method(
          #sqliteAny,
          [],
        ),
        returnValue: _FakeColumnBuilder_32<_i2.DriftAny>(
          this,
          Invocation.method(
            #sqliteAny,
            [],
          ),
        ),
      ) as _i2.ColumnBuilder<_i2.DriftAny>);

  @override
  _i2.ColumnBuilder<T> customType<T extends Object>(
          _i8.UserDefinedSqlType<T>? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #customType,
          [type],
        ),
        returnValue: _FakeColumnBuilder_32<T>(
          this,
          Invocation.method(
            #customType,
            [type],
          ),
        ),
      ) as _i2.ColumnBuilder<T>);

  @override
  _i5.Future<_i3.Plant> mapFromCompanion(
    _i2.Insertable<_i3.Plant>? companion,
    _i2.DatabaseConnectionUser? database,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #mapFromCompanion,
          [
            companion,
            database,
          ],
        ),
        returnValue: _i5.Future<_i3.Plant>.value(_FakePlant_31(
          this,
          Invocation.method(
            #mapFromCompanion,
            [
              companion,
              database,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Plant>);
}

/// A class which mocks [DeleteStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteStatement<T extends _i2.Table, D> extends _i1.Mock
    implements _i2.DeleteStatement<T, D> {
  MockDeleteStatement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseConnectionUser get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i2.ResultSetImplementation<T, D> get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeResultSetImplementation_33<T, D>(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.ResultSetImplementation<T, D>);

  @override
  bool get writeReturningClause => (super.noSuchMethod(
        Invocation.getter(#writeReturningClause),
        returnValue: false,
      ) as bool);

  @override
  set database(_i2.DatabaseConnectionUser? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set table(_i2.ResultSetImplementation<T, D>? _table) => super.noSuchMethod(
        Invocation.setter(
          #table,
          _table,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set whereExpr(_i2.Where? _whereExpr) => super.noSuchMethod(
        Invocation.setter(
          #whereExpr,
          _whereExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set orderByExpr(_i2.OrderBy? _orderByExpr) => super.noSuchMethod(
        Invocation.setter(
          #orderByExpr,
          _orderByExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set limitExpr(_i2.Limit? _limitExpr) => super.noSuchMethod(
        Invocation.setter(
          #limitExpr,
          _limitExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeReturningClause(bool? _writeReturningClause) => super.noSuchMethod(
        Invocation.setter(
          #writeReturningClause,
          _writeReturningClause,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeStartPart(_i2.GenerationContext? ctx) => super.noSuchMethod(
        Invocation.method(
          #writeStartPart,
          [ctx],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<int> delete(_i2.Insertable<D>? entity) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [entity],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<D?> deleteReturning(_i2.Insertable<D>? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteReturning,
          [entity],
        ),
        returnValue: _i5.Future<D?>.value(),
      ) as _i5.Future<D?>);

  @override
  _i5.Future<int> go() => (super.noSuchMethod(
        Invocation.method(
          #go,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<D>> goAndReturn() => (super.noSuchMethod(
        Invocation.method(
          #goAndReturn,
          [],
        ),
        returnValue: _i5.Future<List<D>>.value(<D>[]),
      ) as _i5.Future<List<D>>);

  @override
  void writeInto(_i2.GenerationContext? context) => super.noSuchMethod(
        Invocation.method(
          #writeInto,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GenerationContext constructQuery() => (super.noSuchMethod(
        Invocation.method(
          #constructQuery,
          [],
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #constructQuery,
            [],
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  void where(_i2.Expression<bool> Function(T)? filter) => super.noSuchMethod(
        Invocation.method(
          #where,
          [filter],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UpdateStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateStatement<T extends _i2.Table, D> extends _i1.Mock
    implements _i2.UpdateStatement<T, D> {
  MockUpdateStatement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseConnectionUser get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i2.ResultSetImplementation<T, D> get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeResultSetImplementation_33<T, D>(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.ResultSetImplementation<T, D>);

  @override
  bool get writeReturningClause => (super.noSuchMethod(
        Invocation.getter(#writeReturningClause),
        returnValue: false,
      ) as bool);

  @override
  set database(_i2.DatabaseConnectionUser? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set table(_i2.ResultSetImplementation<T, D>? _table) => super.noSuchMethod(
        Invocation.setter(
          #table,
          _table,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set whereExpr(_i2.Where? _whereExpr) => super.noSuchMethod(
        Invocation.setter(
          #whereExpr,
          _whereExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set orderByExpr(_i2.OrderBy? _orderByExpr) => super.noSuchMethod(
        Invocation.setter(
          #orderByExpr,
          _orderByExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set limitExpr(_i2.Limit? _limitExpr) => super.noSuchMethod(
        Invocation.setter(
          #limitExpr,
          _limitExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeReturningClause(bool? _writeReturningClause) => super.noSuchMethod(
        Invocation.setter(
          #writeReturningClause,
          _writeReturningClause,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeStartPart(_i2.GenerationContext? ctx) => super.noSuchMethod(
        Invocation.method(
          #writeStartPart,
          [ctx],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<int> write(
    _i2.Insertable<D>? entity, {
    bool? dontExecute = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [entity],
          {#dontExecute: dontExecute},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<D>> writeReturning(_i2.Insertable<D>? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #writeReturning,
          [entity],
        ),
        returnValue: _i5.Future<List<D>>.value(<D>[]),
      ) as _i5.Future<List<D>>);

  @override
  _i5.Future<bool> replace(
    _i2.Insertable<D>? entity, {
    bool? dontExecute = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [entity],
          {#dontExecute: dontExecute},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  void writeInto(_i2.GenerationContext? context) => super.noSuchMethod(
        Invocation.method(
          #writeInto,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GenerationContext constructQuery() => (super.noSuchMethod(
        Invocation.method(
          #constructQuery,
          [],
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #constructQuery,
            [],
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  void where(_i2.Expression<bool> Function(T)? filter) => super.noSuchMethod(
        Invocation.method(
          #where,
          [filter],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [InsertStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockInsertStatement<T extends _i2.Table, D> extends _i1.Mock
    implements _i2.InsertStatement<T, D> {
  MockInsertStatement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseConnectionUser get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i2.TableInfo<T, D> get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeTableInfo_34<T, D>(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.TableInfo<T, D>);

  @override
  _i5.Future<int> insert(
    _i2.Insertable<D>? entity, {
    _i2.InsertMode? mode,
    _i2.UpsertClause<T, D>? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [entity],
          {
            #mode: mode,
            #onConflict: onConflict,
          },
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> insertFromSelect(
    _i2.BaseSelectStatement<dynamic>? select, {
    required Map<_i2.Column<Object>, _i2.Expression<Object>>? columns,
    _i2.InsertMode? mode = _i2.InsertMode.insert,
    _i2.UpsertClause<T, D>? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFromSelect,
          [select],
          {
            #columns: columns,
            #mode: mode,
            #onConflict: onConflict,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<D> insertReturning(
    _i2.Insertable<D>? entity, {
    _i2.InsertMode? mode,
    _i2.UpsertClause<T, D>? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertReturning,
          [entity],
          {
            #mode: mode,
            #onConflict: onConflict,
          },
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<D>(
                this,
                Invocation.method(
                  #insertReturning,
                  [entity],
                  {
                    #mode: mode,
                    #onConflict: onConflict,
                  },
                ),
              ),
              (D v) => _i5.Future<D>.value(v),
            ) ??
            _FakeFuture_19<D>(
              this,
              Invocation.method(
                #insertReturning,
                [entity],
                {
                  #mode: mode,
                  #onConflict: onConflict,
                },
              ),
            ),
      ) as _i5.Future<D>);

  @override
  _i5.Future<D?> insertReturningOrNull(
    _i2.Insertable<D>? entity, {
    _i2.InsertMode? mode,
    _i2.UpsertClause<T, D>? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertReturningOrNull,
          [entity],
          {
            #mode: mode,
            #onConflict: onConflict,
          },
        ),
        returnValue: _i5.Future<D?>.value(),
      ) as _i5.Future<D?>);

  @override
  _i5.Future<int> insertOnConflictUpdate(_i2.Insertable<D>? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertOnConflictUpdate,
          [entity],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i2.GenerationContext createContext(
    _i2.Insertable<D>? entry,
    _i2.InsertMode? mode, {
    _i2.UpsertClause<T, D>? onConflict,
    bool? returning = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createContext,
          [
            entry,
            mode,
          ],
          {
            #onConflict: onConflict,
            #returning: returning,
          },
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #createContext,
            [
              entry,
              mode,
            ],
            {
              #onConflict: onConflict,
              #returning: returning,
            },
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  void writeInsertable(
    _i2.GenerationContext? ctx,
    Map<String, _i2.Expression<Object>>? map,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #writeInsertable,
          [
            ctx,
            map,
          ],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SimpleSelectStatement].
///
/// See the documentation for Mockito's code generation for more information.
class MockSimpleSelectStatement<T extends _i2.HasResultSet, D> extends _i1.Mock
    implements _i2.SimpleSelectStatement<T, D> {
  MockSimpleSelectStatement() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get distinct => (super.noSuchMethod(
        Invocation.getter(#distinct),
        returnValue: false,
      ) as bool);

  @override
  Set<_i2.ResultSetImplementation<dynamic, dynamic>> get watchedTables =>
      (super.noSuchMethod(
        Invocation.getter(#watchedTables),
        returnValue: <_i2.ResultSetImplementation<dynamic, dynamic>>{},
      ) as Set<_i2.ResultSetImplementation<dynamic, dynamic>>);

  @override
  _i2.DatabaseConnectionUser get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabaseConnectionUser_17(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.DatabaseConnectionUser);

  @override
  _i2.ResultSetImplementation<T, D> get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeResultSetImplementation_33<T, D>(
          this,
          Invocation.getter(#table),
        ),
      ) as _i2.ResultSetImplementation<T, D>);

  @override
  bool get writeReturningClause => (super.noSuchMethod(
        Invocation.getter(#writeReturningClause),
        returnValue: false,
      ) as bool);

  @override
  set database(_i2.DatabaseConnectionUser? _database) => super.noSuchMethod(
        Invocation.setter(
          #database,
          _database,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set table(_i2.ResultSetImplementation<T, D>? _table) => super.noSuchMethod(
        Invocation.setter(
          #table,
          _table,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set whereExpr(_i2.Where? _whereExpr) => super.noSuchMethod(
        Invocation.setter(
          #whereExpr,
          _whereExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set orderByExpr(_i2.OrderBy? _orderByExpr) => super.noSuchMethod(
        Invocation.setter(
          #orderByExpr,
          _orderByExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set limitExpr(_i2.Limit? _limitExpr) => super.noSuchMethod(
        Invocation.setter(
          #limitExpr,
          _limitExpr,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set writeReturningClause(bool? _writeReturningClause) => super.noSuchMethod(
        Invocation.setter(
          #writeReturningClause,
          _writeReturningClause,
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeStartPart(_i2.GenerationContext? ctx) => super.noSuchMethod(
        Invocation.method(
          #writeStartPart,
          [ctx],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<List<D>> get() => (super.noSuchMethod(
        Invocation.method(
          #get,
          [],
        ),
        returnValue: _i5.Future<List<D>>.value(<D>[]),
      ) as _i5.Future<List<D>>);

  @override
  _i5.Stream<List<D>> watch() => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
        ),
        returnValue: _i5.Stream<List<D>>.empty(),
      ) as _i5.Stream<List<D>>);

  @override
  _i2.JoinedSelectStatement<_i2.HasResultSet, dynamic> join(
          List<_i2.Join<_i2.HasResultSet, dynamic>>? joins) =>
      (super.noSuchMethod(
        Invocation.method(
          #join,
          [joins],
        ),
        returnValue: _FakeJoinedSelectStatement_23<_i2.HasResultSet, dynamic>(
          this,
          Invocation.method(
            #join,
            [joins],
          ),
        ),
      ) as _i2.JoinedSelectStatement<_i2.HasResultSet, dynamic>);

  @override
  _i2.JoinedSelectStatement<_i2.HasResultSet, dynamic> addColumns(
          List<_i2.Expression<Object>>? expressions) =>
      (super.noSuchMethod(
        Invocation.method(
          #addColumns,
          [expressions],
        ),
        returnValue: _FakeJoinedSelectStatement_23<_i2.HasResultSet, dynamic>(
          this,
          Invocation.method(
            #addColumns,
            [expressions],
          ),
        ),
      ) as _i2.JoinedSelectStatement<_i2.HasResultSet, dynamic>);

  @override
  void orderBy(List<_i2.OrderClauseGenerator<T>>? clauses) =>
      super.noSuchMethod(
        Invocation.method(
          #orderBy,
          [clauses],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void writeInto(_i2.GenerationContext? context) => super.noSuchMethod(
        Invocation.method(
          #writeInto,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.GenerationContext constructQuery() => (super.noSuchMethod(
        Invocation.method(
          #constructQuery,
          [],
        ),
        returnValue: _FakeGenerationContext_27(
          this,
          Invocation.method(
            #constructQuery,
            [],
          ),
        ),
      ) as _i2.GenerationContext);

  @override
  void where(_i2.Expression<bool> Function(T)? filter) => super.noSuchMethod(
        Invocation.method(
          #where,
          [filter],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void limit(
    int? limit, {
    int? offset,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #limit,
          [limit],
          {#offset: offset},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<D> getSingle() => (super.noSuchMethod(
        Invocation.method(
          #getSingle,
          [],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<D>(
                this,
                Invocation.method(
                  #getSingle,
                  [],
                ),
              ),
              (D v) => _i5.Future<D>.value(v),
            ) ??
            _FakeFuture_19<D>(
              this,
              Invocation.method(
                #getSingle,
                [],
              ),
            ),
      ) as _i5.Future<D>);

  @override
  _i5.Stream<D> watchSingle() => (super.noSuchMethod(
        Invocation.method(
          #watchSingle,
          [],
        ),
        returnValue: _i5.Stream<D>.empty(),
      ) as _i5.Stream<D>);

  @override
  _i5.Future<D?> getSingleOrNull() => (super.noSuchMethod(
        Invocation.method(
          #getSingleOrNull,
          [],
        ),
        returnValue: _i5.Future<D?>.value(),
      ) as _i5.Future<D?>);

  @override
  _i5.Stream<D?> watchSingleOrNull() => (super.noSuchMethod(
        Invocation.method(
          #watchSingleOrNull,
          [],
        ),
        returnValue: _i5.Stream<D?>.empty(),
      ) as _i5.Stream<D?>);

  @override
  _i2.Selectable<N> map<N>(N Function(D)? mapper) => (super.noSuchMethod(
        Invocation.method(
          #map,
          [mapper],
        ),
        returnValue: _FakeSelectable_26<N>(
          this,
          Invocation.method(
            #map,
            [mapper],
          ),
        ),
      ) as _i2.Selectable<N>);

  @override
  _i2.Selectable<N> asyncMap<N>(_i5.FutureOr<N> Function(D)? mapper) =>
      (super.noSuchMethod(
        Invocation.method(
          #asyncMap,
          [mapper],
        ),
        returnValue: _FakeSelectable_26<N>(
          this,
          Invocation.method(
            #asyncMap,
            [mapper],
          ),
        ),
      ) as _i2.Selectable<N>);
}

/// A class which mocks [$AppDatabaseManager].
///
/// See the documentation for Mockito's code generation for more information.
class Mock$AppDatabaseManager extends _i1.Mock
    implements _i3.$AppDatabaseManager {
  Mock$AppDatabaseManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.$$EventTypesTableTableManager get eventTypes => (super.noSuchMethod(
        Invocation.getter(#eventTypes),
        returnValue: _Fake$$EventTypesTableTableManager_35(
          this,
          Invocation.getter(#eventTypes),
        ),
      ) as _i3.$$EventTypesTableTableManager);

  @override
  _i3.$$SpeciesTableTableManager get species => (super.noSuchMethod(
        Invocation.getter(#species),
        returnValue: _Fake$$SpeciesTableTableManager_36(
          this,
          Invocation.getter(#species),
        ),
      ) as _i3.$$SpeciesTableTableManager);

  @override
  _i3.$$PlantsTableTableManager get plants => (super.noSuchMethod(
        Invocation.getter(#plants),
        returnValue: _Fake$$PlantsTableTableManager_37(
          this,
          Invocation.getter(#plants),
        ),
      ) as _i3.$$PlantsTableTableManager);

  @override
  _i3.$$SpeciesSynonymsTableTableManager get speciesSynonyms =>
      (super.noSuchMethod(
        Invocation.getter(#speciesSynonyms),
        returnValue: _Fake$$SpeciesSynonymsTableTableManager_38(
          this,
          Invocation.getter(#speciesSynonyms),
        ),
      ) as _i3.$$SpeciesSynonymsTableTableManager);

  @override
  _i3.$$SpeciesCareTableTableManager get speciesCare => (super.noSuchMethod(
        Invocation.getter(#speciesCare),
        returnValue: _Fake$$SpeciesCareTableTableManager_39(
          this,
          Invocation.getter(#speciesCare),
        ),
      ) as _i3.$$SpeciesCareTableTableManager);

  @override
  _i3.$$EventsTableTableManager get events => (super.noSuchMethod(
        Invocation.getter(#events),
        returnValue: _Fake$$EventsTableTableManager_40(
          this,
          Invocation.getter(#events),
        ),
      ) as _i3.$$EventsTableTableManager);

  @override
  _i3.$$RemindersTableTableManager get reminders => (super.noSuchMethod(
        Invocation.getter(#reminders),
        returnValue: _Fake$$RemindersTableTableManager_41(
          this,
          Invocation.getter(#reminders),
        ),
      ) as _i3.$$RemindersTableTableManager);

  @override
  _i3.$$ImagesTableTableManager get images => (super.noSuchMethod(
        Invocation.getter(#images),
        returnValue: _Fake$$ImagesTableTableManager_42(
          this,
          Invocation.getter(#images),
        ),
      ) as _i3.$$ImagesTableTableManager);

  @override
  _i3.$$UserSettingsTableTableManager get userSettings => (super.noSuchMethod(
        Invocation.getter(#userSettings),
        returnValue: _Fake$$UserSettingsTableTableManager_43(
          this,
          Invocation.getter(#userSettings),
        ),
      ) as _i3.$$UserSettingsTableTableManager);
}
