// Mocks generated by Mockito 5.4.6 from annotations
// in plant_it/test/ui/settings/settings_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:drift/drift.dart' as _i3;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:plant_it/data/repository/notifications_lang_repository.dart'
    as _i12;
import 'package:plant_it/data/repository/reminder_repository.dart' as _i9;
import 'package:plant_it/data/repository/user_setting_repository.dart' as _i5;
import 'package:plant_it/data/service/notification_service.dart' as _i11;
import 'package:plant_it/data/service/scheduling_service.dart' as _i10;
import 'package:plant_it/data/service/search/cache/app_cache.dart' as _i13;
import 'package:plant_it/data/service/search/flora_codex_searcher.dart' as _i14;
import 'package:plant_it/database/database.dart' as _i2;
import 'package:plant_it/domain/models/species_searcher_result.dart' as _i15;
import 'package:result_dart/result_dart.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTableInfo_1<TableDsl extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.TableInfo<TableDsl, D> {
  _FakeTableInfo_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidNotificationDetails_2 extends _i1.SmartFake
    implements _i4.AndroidNotificationDetails {
  _FakeAndroidNotificationDetails_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserSettingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserSettingRepository extends _i1.Mock
    implements _i5.UserSettingRepository {
  MockUserSettingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.AppDatabase);

  @override
  _i6.Future<_i7.ResultDart<String, Exception>> getOrDefault(
    String? key,
    String? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrDefault,
          [
            key,
            defaultValue,
          ],
        ),
        returnValue: _i6.Future<_i7.ResultDart<String, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getOrDefault,
            [
              key,
              defaultValue,
            ],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<String, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> put(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #put,
            [
              key,
              value,
            ],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<bool, Exception>> exists(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [key],
        ),
        returnValue: _i6.Future<_i7.ResultDart<bool, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #exists,
            [key],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<bool, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<List<_i2.UserSetting>, Exception>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i6
            .Future<_i7.ResultDart<List<_i2.UserSetting>, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<List<_i2.UserSetting>, Exception>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<List<_i2.UserSetting>, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> remove(String? key) =>
      (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #remove,
            [key],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);
}

/// A class which mocks [ReminderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockReminderRepository extends _i1.Mock
    implements _i9.ReminderRepository {
  MockReminderRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TableInfo<_i3.Table, _i2.Reminder> get table => (super.noSuchMethod(
        Invocation.getter(#table),
        returnValue: _FakeTableInfo_1<_i3.Table, _i2.Reminder>(
          this,
          Invocation.getter(#table),
        ),
      ) as _i3.TableInfo<_i3.Table, _i2.Reminder>);

  @override
  _i2.AppDatabase get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.AppDatabase);

  @override
  _i6.Future<_i7.ResultDart<bool, Exception>> updateLastNotified(
          _i2.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLastNotified,
          [reminder],
        ),
        returnValue: _i6.Future<_i7.ResultDart<bool, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #updateLastNotified,
            [reminder],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<bool, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>> getFiltered(
    List<int>? plantIds,
    List<int>? eventTypeIds,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFiltered,
          [
            plantIds,
            eventTypeIds,
          ],
        ),
        returnValue:
            _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>>.value(
                _i8.dummyValue<_i7.ResultDart<List<_i2.Reminder>, Exception>>(
          this,
          Invocation.method(
            #getFiltered,
            [
              plantIds,
              eventTypeIds,
            ],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>> getAll() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>>.value(
                _i8.dummyValue<_i7.ResultDart<List<_i2.Reminder>, Exception>>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<List<_i2.Reminder>, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<_i2.Reminder, Exception>> get(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i6.Future<_i7.ResultDart<_i2.Reminder, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<_i2.Reminder, Exception>>(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<_i2.Reminder, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<int, Exception>> insert(
          _i3.UpdateCompanion<_i2.Reminder>? toInsert) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [toInsert],
        ),
        returnValue: _i6.Future<_i7.ResultDart<int, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #insert,
            [toInsert],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<int, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> delete(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #delete,
            [id],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<bool, Exception>> update(
          _i3.UpdateCompanion<_i2.Reminder>? updated) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [updated],
        ),
        returnValue: _i6.Future<_i7.ResultDart<bool, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #update,
            [updated],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<bool, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> insertAll(
          List<_i3.UpdateCompanion<_i2.Reminder>>? toInsert) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAll,
          [toInsert],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #insertAll,
            [toInsert],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);
}

/// A class which mocks [SchedulingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSchedulingService extends _i1.Mock implements _i10.SchedulingService {
  MockSchedulingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> updateSchedule() => (super.noSuchMethod(
        Invocation.method(
          #updateSchedule,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i11.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<String> get notificationEmoji => (super.noSuchMethod(
        Invocation.getter(#notificationEmoji),
        returnValue: <String>[],
      ) as List<String>);

  @override
  _i4.AndroidNotificationDetails get notificationDetails => (super.noSuchMethod(
        Invocation.getter(#notificationDetails),
        returnValue: _FakeAndroidNotificationDetails_2(
          this,
          Invocation.getter(#notificationDetails),
        ),
      ) as _i4.AndroidNotificationDetails);

  @override
  _i6.Future<bool?> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<bool?>.value(),
      ) as _i6.Future<bool?>);

  @override
  void requireNotificationPermission() => super.noSuchMethod(
        Invocation.method(
          #requireNotificationPermission,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> sendDueReminderNotifications() => (super.noSuchMethod(
        Invocation.method(
          #sendDueReminderNotifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NotificationsLangRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsLangRepository extends _i1.Mock
    implements _i12.NotificationsLangRepository {
  MockNotificationsLangRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get db => (super.noSuchMethod(
        Invocation.getter(#db),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#db),
        ),
      ) as _i2.AppDatabase);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> put(
    bool? isTitle,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            isTitle,
            value,
          ],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #put,
            [
              isTitle,
              value,
            ],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<String, Exception>> getRandomTitle() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomTitle,
          [],
        ),
        returnValue: _i6.Future<_i7.ResultDart<String, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getRandomTitle,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<String, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<String, Exception>> getRandomBody() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRandomBody,
          [],
        ),
        returnValue: _i6.Future<_i7.ResultDart<String, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<String, Exception>>(
          this,
          Invocation.method(
            #getRandomBody,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<String, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<int, Exception>> count() => (super.noSuchMethod(
        Invocation.method(
          #count,
          [],
        ),
        returnValue: _i6.Future<_i7.ResultDart<int, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<int, Exception>>(
          this,
          Invocation.method(
            #count,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<int, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<bool, Exception>> isEmpty() => (super.noSuchMethod(
        Invocation.method(
          #isEmpty,
          [],
        ),
        returnValue: _i6.Future<_i7.ResultDart<bool, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<bool, Exception>>(
          this,
          Invocation.method(
            #isEmpty,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<bool, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<void, Exception>> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<_i7.ResultDart<void, Exception>>.value(
            _i8.dummyValue<_i7.ResultDart<void, Exception>>(
          this,
          Invocation.method(
            #clear,
            [],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<void, Exception>>);
}

/// A class which mocks [AppCache].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppCache extends _i1.Mock implements _i13.AppCache {
  MockAppCache() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> saveSpeciesDetails(
    String? id,
    _i2.SpeciesDataSource? source,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSpeciesDetails,
          [
            id,
            source,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveSpeciesSearch(
    String? term,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveSpeciesSearch,
          [
            term,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  String? getSpeciesDetails(
    String? id,
    _i2.SpeciesDataSource? source,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getSpeciesDetails,
        [
          id,
          source,
        ],
      )) as String?);

  @override
  String? getSpeciesSearch(String? term) =>
      (super.noSuchMethod(Invocation.method(
        #getSpeciesSearch,
        [term],
      )) as String?);

  @override
  _i6.Future<bool> deleteSpeciesDetails(
    String? id,
    _i2.SpeciesDataSource? source,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSpeciesDetails,
          [
            id,
            source,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> deleteSpeciesSearch(String? term) => (super.noSuchMethod(
        Invocation.method(
          #deleteSpeciesSearch,
          [term],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> clearSearch() => (super.noSuchMethod(
        Invocation.method(
          #clearSearch,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearDetails(
    int? id,
    _i2.SpeciesDataSource? source,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #clearDetails,
          [
            id,
            source,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [FloraCodexSearcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockFloraCodexSearcher extends _i1.Mock
    implements _i14.FloraCodexSearcher {
  MockFloraCodexSearcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get version => (super.noSuchMethod(
        Invocation.getter(#version),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#version),
        ),
      ) as String);

  @override
  void setKey(String? key) => super.noSuchMethod(
        Invocation.method(
          #setKey,
          [key],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<
      _i7
      .ResultDart<List<_i15.SpeciesSearcherPartialResult>, Exception>> search(
    String? term,
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [
            term,
            offset,
            limit,
          ],
        ),
        returnValue: _i6.Future<
            _i7.ResultDart<List<_i15.SpeciesSearcherPartialResult>,
                Exception>>.value(_i8.dummyValue<
            _i7.ResultDart<List<_i15.SpeciesSearcherPartialResult>, Exception>>(
          this,
          Invocation.method(
            #search,
            [
              term,
              offset,
              limit,
            ],
          ),
        )),
      ) as _i6.Future<
          _i7.ResultDart<List<_i15.SpeciesSearcherPartialResult>, Exception>>);

  @override
  _i6.Future<_i7.ResultDart<_i15.SpeciesSearcherResult, Exception>> getDetails(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDetails,
          [id],
        ),
        returnValue: _i6.Future<
                _i7.ResultDart<_i15.SpeciesSearcherResult, Exception>>.value(
            _i8.dummyValue<
                _i7.ResultDart<_i15.SpeciesSearcherResult, Exception>>(
          this,
          Invocation.method(
            #getDetails,
            [id],
          ),
        )),
      ) as _i6.Future<_i7.ResultDart<_i15.SpeciesSearcherResult, Exception>>);
}
