serverName: plantitserver
dbName: plantitdatabase
cacheName: plantitcache

dbMountPath: /var/lib/mysql
dbMountCapacity: 512Mi

secret:
  name: plantitsecret
  data:
    MYSQL_PSW: cm9vdA==
    MYSQL_ROOT_PASSWORD: cm9vdA==
    JWT_SECRET: cHV0VGhlU2VjcmV0SGVyZQ==
    FLORACODEX_KEY: 

configmap:
  name: plantitconfigmap
  data:
    MYSQL_HOST: db-service
    MYSQL_PORT: 3306
    MYSQL_USERNAME: root
    MYSQL_DATABASE: bootdb
    JWT_EXP: 1
    USERS_LIMIT: -1
    UPLOAD_DIR: /upload-dir
    API_PORT: 8080
    LOG_LEVEL: DEBUG
    ALLOWED_ORIGINS: "*"
    CACHE_TTL: 86400
    CACHE_HOST: cache-service
    CACHE_PORT: 6379

image:
  server:
    name: msdeluise/plant-it-server
    tag: latest
  db:
    name: mysql
    tag: 8.0
  cache:
    name: redis
    tag: 7.2.1
