name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 90
          days-before-close: 14
          exempt-issue-labels: 'Type: Feature Request'
          stale-issue-message: 'This issue has been marked as stale due to no activity in the last 90 days. It will be closed in 14 days if no further activity occurs.'
          stale-pr-message: 'This pull request has been marked as stale due to no activity in the last 90 days. It will be closed in 14 days if no further activity occurs.'
          close-issue-message: 'Closing this issue as it has been stale for 14 days.'
          close-pr-message: 'Closing this pull request as it has been stale for 14 days.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          operations-per-run: 30
          remove-issue-stale-when-updated: true
          remove-pr-stale-when-updated: true
          exempt-issue-author: 'dependabot[bot]'
          exempt-pr-author: 'dependabot[bot]'
